import type { Metadata } from "next";
import { AuditYearPage } from "@/lib/sercotec-audit/AuditYearPage";
import type { AuditPageData } from "@/lib/sercotec-audit/types";

export const metadata: Metadata = {
  title: "Auditoría Sercotec 2024"
};

const data = {
  year: 2024,
  title: "Auditoría Sercotec 2024",
  subtitle:
    "Revisión tipada de programas 2024, con foco en duplicidades, filas vacías, inconsistencias de fecha y exposición acumulada cuando existe monto máximo parametrizado.",
  summary: {
    year: 2024,
    uploadedFilesInYear: 15,
    rows: 61756,
    usableNamedRows: 52353,
    programs: 13,
    directFundRows: 6419,
    knownAmountRows: 4481,
    knownAmountDuplicateGroups: 16,
    directFundDuplicateGroups: 32,
    sameProgramDuplicateGroups: 102,
    exactDuplicateRows: 21454,
    duplicateNameRows: 21466,
    emptyNameRows: 9403,
    missingNumeroActoRows: 117,
    identitySplitNoAplicaRows: 52106,
    yearMismatchRows: 5,
    knownAmountExposureClpSumAcrossDuplicateGroups: 95200000,
    highestKnownAmountExposureClp: 6200000,
    anomalyRows: 15,
    criticalAnomalyRows: 1,
    highAnomalyRows: 13
  },
  programs: [
    {
      year: 2024,
      program: "Servicios Virtuales",
      rawPrograms: "Servicios Virtuales",
      sourceFiles: "TransparenciaActiva (25).csv",
      rows: 45217,
      usableNamedRows: 45217,
      uniqueNames: 23857,
      exactDuplicateRows: 21360,
      duplicateNameRows: 21360,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 45217,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 9226,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "servicio virtual sin monto directo"
    },
    {
      year: 2024,
      program: "Centros de Desarrollo de Negocios",
      rawPrograms: "Centros de Desarrollo de Negocios",
      sourceFiles: "TransparenciaActiva (28).csv | TransparenciaActiva (29).csv",
      rows: 9400,
      usableNamedRows: 0,
      uniqueNames: 0,
      exactDuplicateRows: 93,
      duplicateNameRows: 0,
      emptyNameRows: 9400,
      missingNumeroActoRows: 117,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "operación/servicio de centros sin beneficiario monetario directo"
    },
    {
      year: 2024,
      program: "Emergencia",
      rawPrograms: "Emergencia",
      sourceFiles: "TransparenciaActiva (24).csv",
      rows: 1690,
      usableNamedRows: 1689,
      uniqueNames: 1686,
      exactDuplicateRows: 1,
      duplicateNameRows: 3,
      emptyNameRows: 1,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 1690,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 608,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "subsidio/emergencia con monto no parametrizado"
    },
    {
      year: 2024,
      program: "Crece",
      rawPrograms: "Crece",
      sourceFiles: "TransparenciaActiva (19).csv",
      rows: 1309,
      usableNamedRows: 1309,
      uniqueNames: 1309,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 1309,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 105,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 5000000,
      amountMaxLabel: "$5.000.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2024,
      program: "Capital Abeja Emprende",
      rawPrograms: "Abeja Emprende",
      sourceFiles: "TransparenciaActiva (23).csv",
      rows: 1171,
      usableNamedRows: 1171,
      uniqueNames: 1073,
      exactDuplicateRows: 0,
      duplicateNameRows: 98,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 1171,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 3500000,
      amountMaxLabel: "$3.500.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2024,
      program: "Capital Semilla Emprende",
      rawPrograms: "Capital Semilla",
      sourceFiles: "TransparenciaActiva (22).csv",
      rows: 1025,
      usableNamedRows: 1025,
      uniqueNames: 1025,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 1025,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 307,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 3500000,
      amountMaxLabel: "$3.500.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2024,
      program: "Ruta Digital Kit Digital",
      rawPrograms: "Ruta Digital",
      sourceFiles: "TransparenciaActiva (20).csv",
      rows: 570,
      usableNamedRows: 570,
      uniqueNames: 570,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 570,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 49,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 1200000,
      amountMaxLabel: "$1.200.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2024,
      program: "Digitaliza tu Almacén",
      rawPrograms: "Digitaliza tu Almacén",
      sourceFiles: "TransparenciaActiva (18).csv",
      rows: 406,
      usableNamedRows: 406,
      uniqueNames: 406,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 406,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 47,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 3000000,
      amountMaxLabel: "$3.000.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2024,
      program: "Promoción y Canales de Comercialización",
      rawPrograms: "Promoción y Canales de Comercialización",
      sourceFiles: "TransparenciaActiva (21).csv",
      rows: 380,
      usableNamedRows: 379,
      uniqueNames: 375,
      exactDuplicateRows: 0,
      duplicateNameRows: 4,
      emptyNameRows: 1,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 380,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 11,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "cofinanciamiento/servicio sin monto individual directo"
    },
    {
      year: 2024,
      program: "Redes de Oportunidades de Negocios",
      rawPrograms: "Redes de Oportunidades de Negocios",
      sourceFiles: "TransparenciaActiva (27).csv",
      rows: 338,
      usableNamedRows: 338,
      uniqueNames: 338,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 338,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 31,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "servicio/redes sin monto directo"
    },
    {
      year: 2024,
      program: "Programa Desarrollo de Ferias Libres",
      rawPrograms: "Desarrollo de Ferias Libres",
      sourceFiles: "TransparenciaActiva (31).csv",
      rows: 127,
      usableNamedRows: 127,
      uniqueNames: 127,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "fondo directo con monto variable/no parametrizado"
    },
    {
      year: 2024,
      program: "Fortalecimiento Gremial",
      rawPrograms: "Fortalecimiento Gremial",
      sourceFiles: "TransparenciaActiva (30).csv",
      rows: 85,
      usableNamedRows: 85,
      uniqueNames: 85,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "fondo gremial con monto variable/no parametrizado"
    },
    {
      year: 2024,
      program: "Fortalecimiento y Creación de Cooperativas",
      rawPrograms: "Fortalecimiento y Creación de Empresas Sociales y Cooperativas | Fortalecimiento y Creación de Empresas sociales y cooperativas",
      sourceFiles: "TransparenciaActiva (17).csv | TransparenciaActiva (32).csv",
      rows: 38,
      usableNamedRows: 37,
      uniqueNames: 36,
      exactDuplicateRows: 0,
      duplicateNameRows: 1,
      emptyNameRows: 1,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 5,
      maleFirstNameFlags: 4,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "fondo cooperativo con monto variable/no parametrizado"
    }
  ],
  anomalies: [
    {
      severity: "crítica",
      category: "duplicación masiva de filas",
      program: "Servicios Virtuales",
      source: "program-summary",
      metric: "exact_duplicate_rows",
      value: 21360,
      evidence: "El programa concentra duplicación exacta y duplicación de nombres a escala masiva dentro del año 2024."
    },
    {
      severity: "alta",
      category: "filas sin beneficiario utilizable",
      program: "Centros de Desarrollo de Negocios",
      source: "program-summary",
      metric: "empty_name_rows",
      value: 9400,
      evidence: "Todas las filas del programa se publican sin beneficiario utilizable para identificar adjudicatarios."
    },
    {
      severity: "alta",
      category: "duplicados de nombre en programa dirigido a mujeres",
      program: "Capital Abeja Emprende",
      source: "program-summary",
      metric: "duplicate_name_rows",
      value: 98,
      evidence: "El programa informa 1.171 filas, 1.073 nombres únicos y 98 duplicados de nombre."
    },
    {
      severity: "alta",
      category: "exposición duplicada con monto conocido",
      program: "Crece | Ruta Digital Kit Digital",
      source: "known-amount-duplicate-detail-rows",
      metric: "known_amount_total_clp",
      value: 6200000,
      evidence: "Los mayores grupos repetidos combinan el monto máximo de Crece y Ruta Digital Kit Digital."
    },
    {
      severity: "alta",
      category: "año inconsistente con fecha de acto",
      program: "Fortalecimiento y Creación de Cooperativas",
      source: "program-summary",
      metric: "year_mismatch_fecha_acto_rows",
      value: 5,
      evidence: "Cinco registros publicados para 2024 tienen año de fecha de acto inconsistente."
    }
  ],
  duplicateExposures: [
    {
      rank: 1,
      displayName: "ASSEMBLAGE SPA",
      normalizedName: "ASSEMBLAGE SPA",
      apparentType: "empresa/organización",
      programCount: 2,
      recordCount: 2,
      programs: "Crece | Ruta Digital Kit Digital",
      knownAmountTotalClp: 6200000,
      firstFechaOtorgamiento: "12-08-2024",
      lastFechaOtorgamiento: "16-10-2024"
    },
    {
      rank: 2,
      displayName: "CERÁMICAS MAGDA SPA",
      normalizedName: "CERAMICAS MAGDA SPA",
      apparentType: "empresa/organización",
      programCount: 2,
      recordCount: 2,
      programs: "Crece | Ruta Digital Kit Digital",
      knownAmountTotalClp: 6200000,
      firstFechaOtorgamiento: "10-10-2024",
      lastFechaOtorgamiento: "13-09-2024"
    },
    {
      rank: 3,
      displayName: "CRECER DE COLORES SPA",
      normalizedName: "CRECER DE COLORES SPA",
      apparentType: "empresa/organización",
      programCount: 2,
      recordCount: 2,
      programs: "Crece | Ruta Digital Kit Digital",
      knownAmountTotalClp: 6200000,
      firstFechaOtorgamiento: "12-08-2024",
      lastFechaOtorgamiento: "19-10-2024"
    }
  ],
  downloads: [
    { label: "Resumen de programas 2024", href: "/data/sercotec2024/analysis/program-summary.csv" },
    { label: "Detalle duplicados con monto 2024", href: "/data/sercotec2024/duplicates/known-amount-duplicate-detail-rows.csv" },
    { label: "Grupos duplicados 2024", href: "/data/sercotec2024/duplicates/known-amount-duplicate-groups.csv" }
  ]
} satisfies AuditPageData;

export default function Sercotec2024Page() {
  return <AuditYearPage data={data} />;
}
