import type { Metadata } from "next";
import { AuditYearPage } from "@/lib/sercotec-audit/AuditYearPage";
import type { AuditPageData } from "@/lib/sercotec-audit/types";

export const metadata: Metadata = {
  title: "Auditoría Sercotec 2023"
};

const data = {
  year: 2023,
  title: "Auditoría Sercotec 2023",
  subtitle:
    "Revisión tipada de programas, archivos fuente, filas útiles, duplicidades, desfases de año y exposición estimada en registros con monto conocido.",
  summary: {
    year: 2023,
    uploadedFilesInYear: 16,
    rows: 52141,
    usableNamedRows: 37806,
    programs: 15,
    directFundRows: 7483,
    knownAmountRows: 5027,
    knownAmountDuplicateGroups: 57,
    directFundDuplicateGroups: 76,
    sameProgramDuplicateGroups: 63,
    exactDuplicateRows: 159,
    duplicateNameRows: 216,
    emptyNameRows: 14335,
    missingNumeroActoRows: 112,
    identitySplitNoAplicaRows: 36312,
    yearMismatchRows: 826,
    knownAmountExposureClpSumAcrossDuplicateGroups: 307500000,
    highestKnownAmountExposureClp: 9500000,
    anomalyRows: 21,
    criticalAnomalyRows: 1,
    highAnomalyRows: 19
  },
  programs: [
    {
      year: 2023,
      program: "Servicios Virtuales",
      rawPrograms: "Servicios Virtuales",
      sourceFiles: "TransparenciaActiva (9).csv",
      rows: 29293,
      usableNamedRows: 29293,
      uniqueNames: 29255,
      exactDuplicateRows: 10,
      duplicateNameRows: 38,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 29293,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 6011,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "servicio virtual sin monto directo"
    },
    {
      year: 2023,
      program: "Centros de Desarrollo de Negocios",
      rawPrograms: "Centros de Desarrollo de Negocios",
      sourceFiles: "TransparenciaActiva (13).csv | TransparenciaActiva (14).csv",
      rows: 14334,
      usableNamedRows: 0,
      uniqueNames: 0,
      exactDuplicateRows: 71,
      duplicateNameRows: 0,
      emptyNameRows: 14334,
      missingNumeroActoRows: 112,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "operación/servicio de centros sin beneficiario monetario directo"
    },
    {
      year: 2023,
      program: "Emergencia",
      rawPrograms: "Emergencia",
      sourceFiles: "TransparenciaActiva (8).csv",
      rows: 2138,
      usableNamedRows: 2137,
      uniqueNames: 2107,
      exactDuplicateRows: 17,
      duplicateNameRows: 30,
      emptyNameRows: 1,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 2138,
      yearMismatchFechaOtorgamientoRows: 521,
      yearMismatchFechaActoRows: 521,
      maleFirstNameFlags: 931,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "subsidio/emergencia con monto no parametrizado"
    },
    {
      year: 2023,
      program: "Crece",
      rawPrograms: "Crece Fondo de Desarrollo de Negocios.",
      sourceFiles: "TransparenciaActiva (3).csv",
      rows: 1548,
      usableNamedRows: 1548,
      uniqueNames: 1548,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 1548,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 134,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 5000000,
      amountMaxLabel: "$5.000.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2023,
      program: "Capital Abeja Emprende",
      rawPrograms: "Capital Abeja Emprende",
      sourceFiles: "TransparenciaActiva (7).csv",
      rows: 1177,
      usableNamedRows: 1177,
      uniqueNames: 1177,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 1,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 3500000,
      amountMaxLabel: "$3.500.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2023,
      program: "Capital Semilla Emprende",
      rawPrograms: "Capital Semilla Emprende",
      sourceFiles: "TransparenciaActiva (6).csv",
      rows: 1019,
      usableNamedRows: 1019,
      uniqueNames: 1019,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 1019,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 312,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 3500000,
      amountMaxLabel: "$3.500.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2023,
      program: "Promoción y Canales de Comercialización",
      rawPrograms: "Promoción y canales de comercialización",
      sourceFiles: "TransparenciaActiva (5).csv",
      rows: 882,
      usableNamedRows: 882,
      uniqueNames: 806,
      exactDuplicateRows: 11,
      duplicateNameRows: 76,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 882,
      yearMismatchFechaOtorgamientoRows: 138,
      yearMismatchFechaActoRows: 138,
      maleFirstNameFlags: 54,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "cofinanciamiento/servicio sin monto individual directo"
    },
    {
      year: 2023,
      program: "Ruta Digital Kit Digital",
      rawPrograms: "Ruta Digital",
      sourceFiles: "TransparenciaActiva (4).csv",
      rows: 467,
      usableNamedRows: 467,
      uniqueNames: 467,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 467,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 19,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 1200000,
      amountMaxLabel: "$1.200.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2023,
      program: "Digitaliza tu Almacén",
      rawPrograms: "Digitaliza tu Almacén",
      sourceFiles: "TransparenciaActiva (1).csv",
      rows: 455,
      usableNamedRows: 455,
      uniqueNames: 455,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 455,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 77,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 3000000,
      amountMaxLabel: "$3.000.000",
      fundingType: "subsidio directo"
    },
    {
      year: 2023,
      program: "Mejora Negocios",
      rawPrograms: "Mejora Negocios",
      sourceFiles: "TransparenciaActiva (10).csv",
      rows: 361,
      usableNamedRows: 361,
      uniqueNames: 326,
      exactDuplicateRows: 32,
      duplicateNameRows: 35,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 361,
      yearMismatchFechaOtorgamientoRows: 121,
      yearMismatchFechaActoRows: 121,
      maleFirstNameFlags: 22,
      isDirectFund: true,
      knownAmount: true,
      amountMaxClp: 1500000,
      amountMaxLabel: "$1.500.000",
      fundingType: "subsidio/cofinanciamiento de asesoría"
    },
    {
      year: 2023,
      program: "Programa Desarrollo de Ferias Libres",
      rawPrograms: "Programa Desarrollo de Ferias Libres",
      sourceFiles: "TransparenciaActiva (16).csv",
      rows: 148,
      usableNamedRows: 148,
      uniqueNames: 148,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 1,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "fondo directo con monto variable/no parametrizado"
    },
    {
      year: 2023,
      program: "Redes de Oportunidades de Negocios",
      rawPrograms: "Redes de Oportunidades de Negocio",
      sourceFiles: "TransparenciaActiva (12).csv",
      rows: 123,
      usableNamedRows: 123,
      uniqueNames: 123,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 123,
      yearMismatchFechaOtorgamientoRows: 40,
      yearMismatchFechaActoRows: 40,
      maleFirstNameFlags: 16,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "servicio/redes sin monto directo"
    },
    {
      year: 2023,
      program: "Fortalecimiento Gremial",
      rawPrograms: "FORTALECIMIENTO GREMIAL Y COOPERATIVO | Fortalecimiento Gremial | Fortalecimiento Gremial 2023 | Fortalecimiento Gremial SERCOTEC 2023 | Fortalecimiento Gremial Ñuble 2023 | Fortalecimiento gremial 2023 | Fortalecimiento gremial 2024",
      sourceFiles: "TransparenciaActiva (15).csv",
      rows: 90,
      usableNamedRows: 90,
      uniqueNames: 90,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "fondo gremial con monto variable/no parametrizado"
    },
    {
      year: 2023,
      program: "Fortalecimiento y Creación de Cooperativas",
      rawPrograms: "Fortalecimiento y Creación de Empresas Sociales y Cooperativas",
      sourceFiles: "TransparenciaActiva (17).csv",
      rows: 81,
      usableNamedRows: 81,
      uniqueNames: 44,
      exactDuplicateRows: 18,
      duplicateNameRows: 37,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 0,
      yearMismatchFechaOtorgamientoRows: 5,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 0,
      isDirectFund: true,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "fondo cooperativo con monto variable/no parametrizado"
    },
    {
      year: 2023,
      program: "Formación Empresarial",
      rawPrograms: "Formación Empresarial",
      sourceFiles: "TransparenciaActiva (11).csv",
      rows: 25,
      usableNamedRows: 25,
      uniqueNames: 25,
      exactDuplicateRows: 0,
      duplicateNameRows: 0,
      emptyNameRows: 0,
      missingNumeroActoRows: 0,
      identitySplitNoAplicaRows: 25,
      yearMismatchFechaOtorgamientoRows: 0,
      yearMismatchFechaActoRows: 0,
      maleFirstNameFlags: 3,
      isDirectFund: false,
      knownAmount: false,
      amountMaxClp: null,
      amountMaxLabel: "Sin monto parametrizado",
      fundingType: "capacitación sin monto individual directo"
    }
  ],
  anomalies: [
    {
      severity: "crítica",
      category: "duplicación exacta de archivo",
      program: "Centros de Desarrollo de Negocios",
      source: "file-duplicate-groups",
      metric: "exact_duplicate_rows",
      value: 71,
      evidence: "Se detectan filas exactamente repetidas entre archivos de Centros, con beneficiarios vacíos y actos administrativos repetidos."
    },
    {
      severity: "alta",
      category: "año inconsistente con fecha",
      program: "Emergencia",
      source: "program-summary",
      metric: "year_mismatch",
      value: 1042,
      evidence: "Año 2023 publicado con fechas de otorgamiento o acto en otro año."
    },
    {
      severity: "alta",
      category: "filas sin beneficiario utilizable",
      program: "Centros de Desarrollo de Negocios",
      source: "program-summary",
      metric: "empty_name_rows",
      value: 14334,
      evidence: "El programa concentra filas sin nombre de beneficiario utilizable para análisis de adjudicatarios."
    },
    {
      severity: "alta",
      category: "duplicados de nombre en programa",
      program: "Fortalecimiento y Creación de Cooperativas",
      source: "program-summary",
      metric: "duplicate_name_rows",
      value: 37,
      evidence: "El mismo programa contiene nombres repetidos pese a informar 81 filas y 44 nombres únicos."
    },
    {
      severity: "alta",
      category: "exposición duplicada con monto conocido",
      program: "Crece | Mejora Negocios",
      source: "known-amount-duplicate-detail-rows",
      metric: "known_amount_total_clp",
      value: 9500000,
      evidence: "Un mismo nombre normalizado aparece en más de un programa con monto máximo conocido acumulado."
    }
  ],
  duplicateExposures: [
    {
      rank: 1,
      displayName: "SOC INMBILIARIA KIWILAND LIMITADA",
      normalizedName: "SOC INMBILIARIA KIWILAND LIMITADA",
      apparentType: "empresa/organización",
      programCount: 2,
      recordCount: 4,
      programs: "Crece | Mejora Negocios",
      knownAmountTotalClp: 9500000,
      firstFechaOtorgamiento: "18-12-2023",
      lastFechaOtorgamiento: "24-07-2023"
    },
    {
      rank: 2,
      displayName: "AGRICOLA LA MAGDALENA LTDA",
      normalizedName: "AGRICOLA LA MAGDALENA LIMITADA",
      apparentType: "empresa/organización",
      programCount: 2,
      recordCount: 2,
      programs: "Crece | Mejora Negocios",
      knownAmountTotalClp: 6500000,
      firstFechaOtorgamiento: "17-10-2023",
      lastFechaOtorgamiento: "24-07-2023"
    },
    {
      rank: 3,
      displayName: "ALDO HERNÁN SANHUEZA REYES",
      normalizedName: "ALDO HERNAN SANHUEZA REYES",
      apparentType: "persona natural o razón social sin forma societaria visible",
      programCount: 2,
      recordCount: 2,
      programs: "Crece | Mejora Negocios",
      knownAmountTotalClp: 6500000,
      firstFechaOtorgamiento: "11-08-2023",
      lastFechaOtorgamiento: "20-12-2023"
    }
  ],
  downloads: [
    { label: "Resumen de programas 2023", href: "/data/sercotec2023/analysis/program-summary.csv" },
    { label: "Detalle duplicados con monto 2023", href: "/data/sercotec2023/duplicates/known-amount-duplicate-detail-rows.csv" },
    { label: "Grupos duplicados 2023", href: "/data/sercotec2023/duplicates/known-amount-duplicate-groups.csv" }
  ]
} satisfies AuditPageData;

export default function Sercotec2023Page() {
  return <AuditYearPage data={data} />;
}
